[build]
  # Build command for React
  command = "npm run build"
  # Directory to publish (React build output)
  publish = "build"
  # Base directory for the build
  base = "client"

[build.environment]
  NODE_VERSION = "18"

# Main redirect rule for SPA (this fixes the 404 issue)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

